### ISSUE TITLE
Genetic test is too slow

### ISSUE THREAD

**Issue by christophlohrmann** [SwarmRL/SwarmRL#58]
On CI, the genetic test takes almost 10 minutes, on my ICP machine more than 20.

![image](https://github.com/SwarmRL/SwarmRL/assets/47663906/402ef8b8-68f0-4e9b-8eb0-83ae0114796b)

**Comment by SamTov** [comment]
:( I will do some tests and make i faster

**Comment by SamTov** [comment]
This should be resolved now, I believe it is under 1 minute.
